#!/usr/bin/env bash
# Rebuilds the MVNDST WebAssembly runtime
#
# Usage: mvndst/build.sh
# Needs: apt-get install f2c libf2c2-dev emscripten
set -euo pipefail

die() { echo "$*" >&2; exit 1; }

root=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
out=$root/../website/src/model/generated
work=$root/.build

hash emcc f2c 2>/dev/null || die "emcc or f2c is missing (apt-get install f2c libf2c2-dev emscripten)"
[[ -f /usr/include/f2c.h ]] || die "f2c.h is missing (apt-get install libf2c2-dev)"

rm -rf "$work"
mkdir -p "$work" "$out"
out=$(cd "$out" && pwd)
# Copy f2c.h next to the generated C so -I "$work" finds it, which keeps
# /usr/include off the include path
cp "$root/vendor/mvndst.f" /usr/include/f2c.h "$work/"
# Remove unused Enthought MVNUN helpers
patch -s -p0 -d "$work" <"$root/vendor/drop-mvnun.patch"

(cd "$work" && f2c -A -a mvndst.f >/dev/null)

emcc -O3 -flto \
  -I "$work" \
  "$work/mvndst.c" "$root/src/mvndst_api.c" \
  -o "$out/mvndst.mjs" \
  -sEXPORT_ES6=1 \
  -sMODULARIZE=1 \
  -sEXPORT_NAME=createMvndst \
  -sENVIRONMENT=web,worker \
  -sEXPORTED_FUNCTIONS=_mvndst_cdf,_malloc,_free \
  -sEXPORTED_RUNTIME_METHODS=HEAPF64 \
  -sINCOMING_MODULE_JS_API=locateFile \
  -sALLOW_MEMORY_GROWTH=1 \
  -sFILESYSTEM=0 \
  -sDYNAMIC_EXECUTION=0 \
  -sSTRICT=1

# emcc's --emit-tsd uses an older TypeScript than in website/, so we write types manually below
cat >"$out/mvndst.d.mts" <<'TSD'
// Generated by mvndst/build.sh. Do not edit.
export interface MvndstModule {
  _mvndst_cdf(
    n: number,
    lower: number,
    upper: number,
    correl: number,
    maxpts: number,
    abseps: number,
    releps: number,
  ): number;
  _malloc(size: number): number;
  _free(ptr: number): void;
  HEAPF64: Float64Array;
}
export default function createMvndst(options?: {
  locateFile?: (path: string) => string;
}): Promise<MvndstModule>;
TSD

printf '\nwrote:\n'
printf '  %s\n' "$out"/mvndst.{mjs,wasm,d.mts}
