"""Build the expected numbers the website's model tests compare against, using CorrectMatch.jl."""

import json
from pathlib import Path

import correctmatch
import numpy as np

cm = correctmatch.cm  # The Julia CorrectMatch module itself, not the Python wrapper.

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT.parent / "website" / "tests" / "fixtures" / "correctmatch_reference.json"

# Sampling rounds per record. More rounds means less random noise in p_avg.
ITER = 40_000
SEED = 20260529
N_ROWS = 20_000
# Use uneven category sizes to cover both common and rare answers.
MARGINALS = [
    [0.6, 0.3, 0.1],
    [0.4, 0.3, 0.15, 0.1, 0.05],
    [0.3, 0.25, 0.15, 0.1, 0.08, 0.06, 0.04, 0.02],
    [0.5, 0.3, 0.15, 0.05],
]


def make_dataset(rng: np.random.Generator) -> np.ndarray:
    """Create test rows whose answers are correlated and unevenly spread across categories."""
    dim = len(MARGINALS)
    cov = np.full((dim, dim), 0.5) + 0.5 * np.eye(dim)
    latent = rng.multivariate_normal(np.zeros(dim), cov, size=N_ROWS)
    out = np.empty((N_ROWS, dim), dtype=np.int64)
    for j, pr in enumerate(MARGINALS):
        cuts = np.quantile(latent[:, j], np.cumsum(pr)[:-1])
        out[:, j] = np.digitize(latent[:, j], cuts) + 1
    return out


def extract_model(m, dim: int) -> tuple[list[list[float]], list[list[float]]]:
    sigma = np.array(correctmatch.jl.getproperty(m, correctmatch.jl.Symbol("Σ")))
    marg = correctmatch.jl.getproperty(m, correctmatch.jl.Symbol("marginals"))
    probs = [np.array(correctmatch.jl.getproperty(marg[i], correctmatch.jl.Symbol("p"))).tolist() for i in range(dim)]
    return sigma.tolist(), probs


def p_avg(m, indiv: np.ndarray, iteration: int) -> float:
    """Estimate, by sampling, how likely this combination of answers is."""
    cells = cm.Individual.smooth_weight(m, indiv, iter=iteration)
    return float(np.mean(np.asarray(cells)))


def main() -> None:
    rng = np.random.default_rng(SEED)
    data = make_dataset(rng)
    dim = data.shape[1]

    m = correctmatch.fit_model(data, exact_marginal=True)
    sigma, probs = extract_model(m, dim)

    model = {
        "iso3": "REF",
        "name": "Synthetic reference",
        "avail_var": [f"v{j}" for j in range(dim)],
        "pop_num": None,
        "corr": sigma,
        "marginals": {
            f"v{j}": {
                "probs": probs[j],
                "uniqVals": list(range(1, len(probs[j]) + 1)),  # category numbers expected by CorrectMatch
            }
            for j in range(dim)
        },
    }

    records = [
        ([1, 1, 1, 1], 200),  # Common answers in a larger group.
        ([3, 5, 8, 4], 20),  # Rare answers in a smaller group.
        ([1, 2, 3, 2], 200),
        ([2, 4, 6, 3], 50),
    ]

    cases = []
    for rec, n in records:
        indiv = np.array(rec, dtype=np.int64)
        pa = p_avg(m, indiv, ITER)
        indiv0 = [c - 1 for c in rec]  # The website counts categories from zero.
        cases.append({"indiv0": indiv0, "n": n, "p_avg": pa, "uniqueness": (1 - pa) ** (n - 1)})

    fixture = {
        "_comment": "Generated by pre-training/src/gen_reference.py from CorrectMatch.jl. "
        "Do not edit by hand; re-run the script to refresh.",
        "iter": ITER,
        "model": model,
        "cases": cases,
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(fixture, indent=2))
    print(f"wrote {OUT.relative_to(ROOT.parent)} with {len(cases)} cases")
    for c in cases:
        print(f"  indiv={c['indiv0']} n={c['n']:>7} p_avg={c['p_avg']:.6f} uniq={c['uniqueness']:.6f}")


if __name__ == "__main__":
    main()
